Repository algolia/algoliasearch-client-python, pull requests merged in 2019-09, with the labels that each got.

#444 feat: adds index exists
  algoliasearch/search_index.py
  algoliasearch/search_index_async.py
  tests/features/test_search_index.py
  tests/unit/test_search_index.py
Labels: API feature, Chore, Do not merge

#452 fix: makes unreachable be an algolia exception
  algoliasearch/exceptions.py
Labels: Bug

#449 feat: unit test relevance
  algoliasearch/exceptions.py
  algoliasearch/http/request_options.py
  algoliasearch/search_index.py
  algoliasearch/search_index_async.py
  tests/features/test_search_index.py
  tests/unit/test_search_index.py
Labels: API feature, Do not merge

#454 fix: adds request_options into exists method
  algoliasearch/search_index.py
  algoliasearch/search_index_async.py
  tests/unit/test_search_index.py
Labels: Bug
